### ISSUE TITLE
Persona working locally

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#181]
Persona doesn't work on my local system. Throws:

`the page at localhost:9000 says: Login failure: INTERNAL SERVER ERROR`
`Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR) http://localhost:9000/auth`
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://gmail.login.persona.org') does not match the recipient window's origin ('https://login.persona.org').`

**Comment by phiden** [comment]
More from the Python logs: 

```
Traceback (most recent call last):
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/public/views.py", line 66, in auth
    user = User.query.filter(User.email == email).first()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2444, in first
    ret = list(self[0:1])
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2280, in __getitem__
    return list(res)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
    return self._execute_and_instances(context)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2528, in _execute_and_instances
    close_with_result=True)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2519, in _connection_from_session
    **kw)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 882, in connection
    execution_options=execution_options)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2034, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2073, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1403, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2069, in _wrap_pool_connect
    return fn()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 708, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1049, in _do_get
    self._dec_overflow()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1046, in _do_get
    return self._create_connection()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/pool.py", line 602, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5432?

```

**Comment by ErnieAtLYD** [comment]
We solved this by going on the localhost, running postgres and then typing in the `python manage.py db migrate` command.
