### ISSUE TITLE
Logging out prompts you to log back in.

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#193]
`http://localhost:9000/login?next=%2Flogout`

Instead of completing the logout and returning you to the dashboard or to a "successfully logged out" page, it pushes you to a page that prompts you to log back in while giving you a message that only MDC users can log in.

**Comment by ErnieAtLYD** [comment]
@phiden are you still seeing this issue?

**Comment by phiden** [comment]
Now I’m not allowed to logout at all. 

```
127.0.0.1 - - [15/Sep/2015 13:27:41] "POST /logout HTTP/1.1" 500 -

Traceback (most recent call last):

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request

    return view_func(**req.view_args)

  File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/public/views.py", line 45, in logout

    return render_template('public/home.html')

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template

    context, ctx.app)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render

    rv = template.render(context)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render

    return self.environment.handle_exception(exc_info, True)

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception

    reraise(exc_type, exc_value, tb)

  File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/templates/public/home.html", line 229, in top-level template code

    {{ '%0.2f'| format(yoy|float) }}%

  File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/templates/layout.html", line 32, in top-level template code

    {% block body %}

  File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/templates/layout.html", line 123, in block "body"

    {% block content %}{% endblock %}

  File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/templates/public/home.html", line 28, in block "content"

    <p class='invisible'>{{ dash_obj[0].data.new_reviews }}</p>

  File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/jinja2/environment.py", line 378, in getitem

    return obj[argument]

UndefinedError: 'dash_obj' is undefined
```
