### ISSUE TITLE
Delete user goes to "internal server error

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#451]
Could lead to users getting accidentally deleted. the edit button should be bigger or contained within the edit user page. Delete user also goes to "internal server error"

![screenshot 2015-10-27 16 47 58](https://cloud.githubusercontent.com/assets/8147336/10772081/952bfea8-7cca-11e5-99c3-856d3c5c4005.png)

**Comment by phiden** [comment]
Styling button is done, but the error's still there. 

`DataError: (psycopg2.DataError) invalid input syntax for integer: "sarasti@miamidade.gov" LINE 3: WHERE users.id = 'sarasti@miamidade.gov' ^ [SQL: 'SELECT users.id AS users_id, users.email AS users_email, users.created_at AS users_created_at, users.full_name AS users_full_name, users.active AS users_active, users.role_id AS users_role_id \nFROM users \nWHERE users.id = %(id_1)s'] [parameters: {'id_1': u'sarasti@miamidade.gov'}]`

**Comment by ErnieAtLYD** [comment]
@phiden is this really done? i merged newest code the edit button is still a link and the delete button still looks like a button. It should be one style or another.

**Comment by phiden** [comment]
I need to submit a PR for this but yes it’s done.

**Comment by phiden** [comment]
Still seeing the error, though. 

```
sqlalchemy.exc.DataError
DataError: (psycopg2.DataError) invalid input syntax for integer: "sarasti@miamidade.gov"
LINE 3: WHERE users.id = 'sarasti@miamidade.gov'
                         ^
 [SQL: 'SELECT users.id AS users_id, users.email AS users_email, users.created_at AS users_created_at, users.full_name AS users_full_name, users.active AS users_active, users.role_id AS users_role_id \nFROM users \nWHERE users.id = %(id_1)s'] [parameters: {'id_1': u'sarasti@miamidade.gov'}]

Traceback (most recent call last)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
return view_func(**req.view_args)
File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/decorators.py", line 23, in decorated_function
return view_function(*args, **kwargs)
File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/user/views.py", line 104, in user_delete
user = get_object_or_404(User, User.id == id)
File "/Users/sophiadengo/Desktop/mdc-feedback/feedback/database.py", line 19, in get_object_or_404
return model.query.filter(*criterion).one()
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2472, in one
ret = list(self)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
return self._execute_and_instances(context)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
compiled_sql, distilled_params
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
context)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
exc_info
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
File "/Users/sophiadengo/.virtualenvs/mdc-feedback-env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
cursor.execute(statement, parameters)
DataError: (psycopg2.DataError) invalid input syntax for integer: "sarasti@miamidade.gov" LINE 3: WHERE users.id = 'sarasti@miamidade.gov' ^ [SQL: 'SELECT users.id AS users_id, users.email AS users_email, users.created_at AS users_created_at, users.full_name AS users_full_name, users.active AS users_active, users.role_id AS users_role_id \nFROM users \nWHERE users.id = %(id_1)s'] [parameters: {'id_1': u'sarasti@miamidade.gov'}]

```

**Comment by phiden** [comment]
![screen shot 2015-10-30 at 8 43 30 am](https://cloud.githubusercontent.com/assets/4895604/10845968/67badd08-7ee2-11e5-82bd-c923acd27b16.png)
